version: '3.7'

services:
  app:
    image: makeabox_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app
    ports:
      - "5001:5001"
    expose:
      - "5001"
    environment:
      RAILS_ENV: "production"

  web:
    image: makeabox_web:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - "app:puma"
    ports:
      - "80:80"
