# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a06ddbf24dc7b05db891c83aa57ec4841ec077b5a7e511c6c78b36db5bb580524b686228adae244cb40b3cf481dbaca37f50c77cca1ff3fd65a8e3b997e4449

test:
  secret_key_base: 36d2389e0c8fbde871c44ecd3f1e8c5b5e7c5e230c6eafb8f4121482db70171b48ba18c3f17937f19aa0857951a48893ea81406f698ef079ecc3ebc45249ea05

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || File.exist?( "#{ENV['HOME']}/.secret_key_base" ) ? File.read("#{ENV["HOME"]}/.secret_key_base").chomp : nil %>
